name: flare_flutter
description: Vector design and runtime animation for Flutter.
version: 1.5.5
author: "2Dimensions Team <info@2dimensions.com>"
homepage: https://github.com/2d-inc/Flare-Flutter
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flare_dart: 
    path: ../flare_dart
dev_dependencies:
  flutter_test:
    sdk: flutter