name: rivtrek
description: "涉川 Rivtrek - 涉川"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pedometer: ^4.0.0
  health: ^11.0.0
  workmanager: ^0.7.0
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  http: ^1.2.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cache: ^1.5.0
  path_provider: ^2.1.4
  dio: ^5.7.0
  sqflite: ^2.3.3+1
  path: ^1.9.0
  provider: ^6.1.1
  rive: ^0.14.2
  timeline_tile: ^2.0.0
  flare_flutter:
    path: dependencies/Flare-Flutter/flare_flutter
  flare_dart:
    path: dependencies/Flare-Flutter/flare_dart
  nima: 
    path: dependencies/Nima-Flutter
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/rivers/
    - assets/icons/
    - assets/geo/rivers/yangtze/
  shaders:
    - shaders/river.frag
    - shaders/river_ink.frag
    - shaders/river_real.frag
    - shaders/river_aurora.frag
