name: river_meet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pedometer: ^4.0.0
  health: ^11.0.0
  workmanager: ^0.9.0+3
  shared_preferences: ^2.5.4
  permission_handler: ^11.4.0
  geolocator: ^13.0.4
  http: ^1.3.0
  flutter_map: ^8.2.0
  latlong2: ^0.9.1
  flutter_map_cache: ^2.0.0+1
  path_provider: ^2.1.5
  dio: ^5.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/rivers/
    - assets/geo/rivers/yangtze/
  shaders:
    - shaders/river.frag
    - shaders/river_ink.frag
